server:
  port: 8082   # Different port than user-service

spring:
  application:
    name: project-service


  datasource:
    url: jdbc:mysql://localhost:3306/project_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: khan1_.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


    logging:
      level:
        org.springframework.cloud.openfeign: DEBUG
        com.khan.project_service: DEBUG

    spring:
      jpa:
        show-sql: true
        properties:
          hibernate:
            format_sql: true

    #eureka server details
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/