server:
  #port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/users_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: khan1_.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: "replace-with-a-256-bit-secret-string-for-jwt-signing"
    expiration-minutes: 120
  storage:
    base-dir: ./uploads/users
  internal:
    api-key: "dev-internal-key"  # used later if you want to protect inter-service endpoints

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

    #eureka server details
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
